# Generated by Django 4.2.13 on 2024-05-10 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 10, 49, 34, 404504, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
