# Generated by Django 4.2.13 on 2024-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
