# Generated by Django 4.2.13 on 2024-05-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0006_alter_product_options_product_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('surname', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('salary', models.PositiveBigIntegerField(default=0)),
                ('per_hour', models.PositiveBigIntegerField(default=0)),
                ('advance_payment', models.PositiveIntegerField(default=0)),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='warehouse.category')),
            ],
        ),
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come', models.DateTimeField(blank=True)),
                ('leave', models.DateTimeField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attandances', to='worker.worker')),
            ],
        ),
    ]
