# Generated by Django 4.2.13 on 2024-05-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='slug',
        ),
    ]
