# Generated by Django 4.2.13 on 2024-05-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_attandance_date_adde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attandance',
            old_name='date_adde',
            new_name='date_added',
        ),
    ]
