# Generated by Django 4.2.13 on 2024-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_alter_attandance_come_alter_attandance_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='come',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attandance',
            name='leave',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
