# Generated by Django 4.2.13 on 2024-05-12 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_sale_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='sale',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
