# Generated by Django 4.2.13 on 2024-05-12 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_sale_options_sale_date_added_sale_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deadline',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
