# Generated by Django 4.2.13 on 2024-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_sale_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='deadline',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
